# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 421)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resource/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.482955 rgba(165, 17, 82, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:10;\n"
"border:3;\n"
"")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/youtube/resource/loge.jpg"))
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.482955 rgba(165, 17, 82, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:2px")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(20, 20))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("border-radius:5")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.comboBox)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.482955 rgba(165, 17, 82, 255), stop:1 rgba(255, 255, 255, 255));")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_4)
        self.open_folder = QtWidgets.QPushButton(self.centralwidget)
        self.open_folder.setMinimumSize(QtCore.QSize(30, 30))
        self.open_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_folder.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{background-color:orange;color:cyan;border-radius:8}\n"
"QPushButton:pressed{background-color:gray;color:yellow;border-radius:6}")
        self.open_folder.setIcon(icon)
        self.open_folder.setCheckable(False)
        self.open_folder.setAutoDefault(False)
        self.open_folder.setDefault(False)
        self.open_folder.setFlat(False)
        self.open_folder.setObjectName("open_folder")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.open_folder)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(20, 20))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.plainTextEdit)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setMinimumSize(QtCore.QSize(30, 30))
        self.download_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_button.setStyleSheet("QPushButton{color:back}\n"
"QPushButton:hover{background-color:darkblue;color:pink;border-radius:10;}\n"
"QPushButton:pressed{background-color:gray;color:yellow;border-radius:10}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resource/download_arrow_14460.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_button.setIcon(icon1)
        self.download_button.setObjectName("download_button")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.download_button)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    border: 2px solid grey;\n"
"    border-radius: 3px;\n"
"    text-align: center;}\n"
"::chunk {\n"
"    background-color: \n"
"    qlineargradient(x0: 0, x2: 1, \n"
"     stop: 0 green, stop: 0.6 green,\n"
"                    stop: 0.8 orange, \n"
"                    stop: 1 red\n"
"                    )};")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.progressBar)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setCursorPosition(29)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_3)
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.comboBox.raise_()
        self.lineEdit_4.raise_()
        self.open_folder.raise_()
        self.plainTextEdit.raise_()
        self.download_button.raise_()
        self.progressBar.raise_()
        self.lineEdit_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Downloader"))
        MainWindow.setStatusTip(_translate("MainWindow", "Введите ссылку на видео"))
        MainWindow.setWhatsThis(_translate("MainWindow", "Введите ссылку на видео"))
        MainWindow.setAccessibleName(_translate("MainWindow", "Введите ссылку на видео"))
        MainWindow.setAccessibleDescription(_translate("MainWindow", "Введите ссылку на видео"))
        self.lineEdit_2.setText(_translate("MainWindow", "YouTube Video Downloader"))
        self.lineEdit.setText(_translate("MainWindow", "Выберите ваше разрешение"))
        self.comboBox.setItemText(0, _translate("MainWindow", "720p"))
        self.comboBox.setItemText(1, _translate("MainWindow", "480p"))
        self.comboBox.setItemText(2, _translate("MainWindow", "360p"))
        self.comboBox.setItemText(3, _translate("MainWindow", "240p"))
        self.comboBox.setItemText(4, _translate("MainWindow", "144p"))
        self.lineEdit_4.setText(_translate("MainWindow", "Выберите папку для сохранения файла"))
        self.open_folder.setText(_translate("MainWindow", "Open folder"))
        self.download_button.setText(_translate("MainWindow", "Download video"))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "Введите ссылку на видео"))
        self.lineEdit_3.setStatusTip(_translate("MainWindow", "Введите ссылку на видео"))
        self.lineEdit_3.setWhatsThis(_translate("MainWindow", "Введите ссылку на видео"))
        self.lineEdit_3.setAccessibleName(_translate("MainWindow", "Введите ссылку на видео"))
        self.lineEdit_3.setAccessibleDescription(_translate("MainWindow", "Введите ссылку на видео"))
import res_rc
